spring:
  application:
    name: service-provider

server:
  port: 7071


# eureka 注册中心
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://root:123456@localhost:8761/eureka # 集群就用逗号写多个
  instance:
    hostname: service-provider-host
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

# 度量指标监控与健康检查
management:
  endpoints:
    web:
      exposure:
        include: shutdown  # 开启shutdown端点访问
  endpoint:
    shutdown:
      enabled: true         # 开启shutdown实现优雅停服
